version: "3.7"

services:
    django:
        image: tipsy-admin:latest
        build: .
        container_name: tipsy-admin
        ports:
            #- "${API_PORT}:${API_PORT}"
            - "8000:8000"
        # env_file:
        #     - .env
        restart: always
        volumes:
            - .:/app
