name: CI/CD Pipline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Tipsy Admin
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Run test
      uses: appleboy/ssh-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        script_stop: true
        script: |
          chmod +x /home/ubuntu/deploy/test.sh && sh /home/ubuntu/deploy/test.sh
          chmod +x /home/ubuntu/deploy/slack_alert.sh && sh /home/ubuntu/deploy/slack_alert.sh

