name: CI/CD Pipline

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build Tipsy Admin
        runs-on: ubuntu-20.04
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.8]

        steps:
            - name: Checkout source code
              uses: actions/checkout@v2
            - name: Copy file to cloud server
              uses: appleboy/scp-action@master
              with:
                  username: ${{ secrets.SERVER_USERNAME }}
                  host: ${{ secrets.SERVER_HOST }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  source: "."
                  target: "/home/ec2-user/program/tipsy-raw-admin"
            - name: Run deploy scripts.
              uses: appleboy/ssh-action@master
              with:
                  username: ${{ secrets.SERVER_USERNAME }}
                  host: ${{ secrets.SERVER_HOST }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script_stop: true
                  script: |
                      chmod +x /home/ec2-user/deploy/deploy_tipsy_admin.sh && sh /home/ubuntu/deploy/deploy_tipsy_admin.sh
